### ISSUE TITLE
Website 

### ISSUE THREAD

**Issue by Karna98** [Karna98/Save-Tabs#23]
1. Simple Static Website
2. Links to Extension on the different chrome/addon store published.
3. Guides.

**Comment by itshoax** [comment]
What you want are you open for pull requests ?

**Comment by Karna98** [comment]
Thanks for the interest @c0derdx. 

I am already working on this issue. 

If you come across any issue, feel free to raise it.

**Comment by itshoax** [comment]
Glad to know that you are active I was looking to do some contribution in open source, so please pull the requests if you find them useful.
