### ISSUE TITLE
Chrome web store

### ISSUE THREAD

**Issue by Chaprnks** [Karna98/Save-Tabs#31]
Yesterday the Chrome Web Store link was working fine. Unfortunately this morning, I tried the link on the desktop & it returns a 404 error. This issue seems to only apply to the chrome link, and the firefox is unaffected.

![raw](https://user-images.githubusercontent.com/6340970/147885935-b9a9a5ca-b6c3-4490-824b-45291f6a76f3.png)

**Comment by Karna98** [comment]
Hi @Chaprnks, 

Can you please elaborate on the steps to reproduce the issue?
From where are you visiting the chrome link? 

There are no recent changes or updates in the extension. Please find attached link for [Save Tabs - Chrome Store](https://chrome.google.com/webstore/detail/save-tabs/ljokfgphjbhjheflldgfmjligcmcmhmn)
