### ISSUE TITLE
Release extension on chromestore

### ISSUE THREAD

**Issue by sladyn98** [Karna98/Save-Tabs#8]
**As a user** I am not very experienced with javascript and would like this extension to be either released on the chrome store or I would like a bash script that automates the instructions in the readme

**Possible Solutions**
a) Release to chrome store ( https://developer.chrome.com/docs/webstore/publish/ )
b) Bash script to run the steps in readme

**Comment by Karna98** [comment]
Chrome Web Store: https://chrome.google.com/webstore/detail/save-tabs/ljokfgphjbhjheflldgfmjligcmcmhmn
Firefox Add-Ons : https://addons.mozilla.org/en-US/firefox/addon/save-tabs/
